[package]
name = "snap-coin-pool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dotenvy = "0.15.7"
envy = "0.4.2"
num-bigint = "0.4.6"
serde = "1.0.228"
serde_json = "1.0.149"
snap-coin = "11.2.2"
tokio = { version = "1.49.0", features = ["full"] }
